// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYX2BSK5gYlBqM5EbpeXPf_WPqoQ5Xg0',
    appId: '1:788834679654:web:90606ce867d2996cfc66a7',
    messagingSenderId: '788834679654',
    projectId: 'shaddai-68df1',
    authDomain: 'shaddai-68df1.firebaseapp.com',
    storageBucket: 'shaddai-68df1.firebasestorage.app',
    measurementId: 'G-CP3H6EZ2GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfzmaH8f0j6CjleVaudHTIUtVa9lpXphc',
    appId: '1:788834679654:android:3c1b01df542ce56afc66a7',
    messagingSenderId: '788834679654',
    projectId: 'shaddai-68df1',
    storageBucket: 'shaddai-68df1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDchk20IA0Z87tC4jpLkLfjOn8Lc8V9ew',
    appId: '1:788834679654:ios:91ec626a4930d755fc66a7',
    messagingSenderId: '788834679654',
    projectId: 'shaddai-68df1',
    storageBucket: 'shaddai-68df1.firebasestorage.app',
    iosBundleId: 'com.juliangg.shaddai',
  );
}
